# Generated by Django 2.2.7 on 2019-11-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='alias',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='urls',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
