# Generated by Django 2.2.7 on 2019-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlery', '0002_auto_20191108_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='alias',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='link',
            field=models.URLField(),
        ),
    ]
